on:
  push:
    branches: main
  pull_request:
  merge_group:

name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true

      - name: microbit V1
        run: cargo clippy --package microbit -- -D warnings

      - name: microbit V2
        run: cargo clippy --package microbit-v2 -- -D warnings
